### PR TITLE
update StringResources.tr.xaml

### PR DESCRIPTION
**Pull request by dagdelenvolkan**
To support localization, Turkish translation added.

### CODE REVIEW

**Comment by NickeManarin** [comment]
Thank you. Would you like to add your name or nickname as the author of this update?

**Comment by dagdelenvolkan** [comment]
That sounds great. But I didn't exactly understand that where I suppose to add my name.

**Comment by NickeManarin** [comment]
You can tell me and I put it there.

**Comment by dagdelenvolkan** [comment]
Okay, then you can add my name as "Volkan Dağdelen". Thank you.

**Comment by NickeManarin** [comment]
Ok, I'll add it. Thanks.

**Pull request merged**
