### PR TITLE
Update StringResources.zh.xaml

### PR DESCRIPTION
**Pull request by shenzhiming88**

### CODE REVIEW

**Comment by shenzhiming88** [comment]
Sorry, I forgot to convert the branch to dev, please change it when you merge it, thanks.

**Comment by NickeManarin** [comment]
It's okay. 

I'm starting to create a branch for each translation update, so I can test that it's working.

**Comment by NickeManarin** [comment]
Btw, I'm planning in creating a better spot in Options/About to put your details.
If you wish so, you can move this info to that spot:

`简体中文翻译 BY 大眼仔~旭（Anan）2021（www.dayanzai.me)`

With something like Language, Name, Date, Author notes, etc.

**Comment by shenzhiming88** [comment]
> Btw, I'm planning in creating a better spot in Options/About to put your details.
> If you wish so, you can move this info to that new spot (once it's created):
> 
> `简体中文翻译 BY 大眼仔~旭（Anan）2021（www.dayanzai.me)`
> 
> With something like Language, Name, Date, Author notes, etc.

Hello!
I did not create this profile and my information does not appear in your project.

**Comment by NickeManarin** [comment]
Oh, so I compared with the wrong commit. Ignore it. :)

**Comment by shenzhiming88** [comment]
> Oh, so I compared with the wrong commit. Ignore it. :)

Hello,
So should I creat a new Pull Request to remove it?

**Pull request merged**
