### PR TITLE
Change Import Video method to use ffmpeg instead.

### PR DESCRIPTION
**Pull request by manbokGo**
#378 

More precise capturing frames from videos.

Progress bar works fine with parsed ffmpeg output with -progress option. This trick could also be applied when you encode gif with ffmpeg. ~~I haven't done it yet.~~ EDIT: Done

In addition, due to laggy, unnecessary video jumping, Start/End time NumericUpDown no longer continuously change their value while dragging Selection Slider. Now only changes value when you finish drag on slider.

I just deleted whole old capturing methods, so ffmpeg is essential to import videos. Display warning status bar when trying to import vid and ffmpeg not set on program, commented out Editor.xaml.cs:4910 StatusList.Remove(~) for this.

I'm not good programmer. It will be very appreciated to improve these code.

### CODE REVIEW

**Comment by NickeManarin** [comment]
Please, message me before doing pull requests.
This way we avoid doing the same work twice.

**Comment by manbokGo** [comment]
Sorry, I haven't thought about it. I made this changes for personal need very impulsively, and I just thought it would be good to share. You can ignore this pull request completely if it conflicts with your work.

**Comment by NickeManarin** [comment]
I'm going to analyze the code ([FFmpeg progress](https://github.com/NickeManarin/ScreenToGif/issues/417)), if you've done better than me, I'm going to use your code or manually merge parts that are better than mine.

I'm not sure if we should completely remove the old video importing methods. My idea was to add FFmpeg as a substitute, if available.

Also, the video preview while dragging (I think) gives a better UX. 
You can see the video without having to release the click. I could tweak the rate in which this happens instead of simply removing it.

But anyway, nice code. Thanks.

**Comment by manbokGo** [comment]
Yes, you're right. I see it's too much deletions/changes. Sorry that my code is too poor to fit in yours. As I said it was quick work in a day. Tweak the rate while preview will be better than my approach surely. Thanks for your effort.

**Comment by NickeManarin** [comment]
Wait, I thank you for your effort in helping the project get better. I just have to analyze the changes beforehand.

I've written that I was going analyze your PR to see if we did the exact same thing or if you did something better than me, so I could decide if I was going to send my version or take yours (of the FFmpef progress implementation)

I haven't said that your code was poor!

The only criticism was the choices of implementation that I always have to think about it and decide if it's the best for the project or not, UX wise.

For example, the standard way of importing could be left as a fallback if the user can't or won't download FFmpeg.

Now the preview while dragging I think is good for getting the right frame start/ending more easily than having to release the mouse. I may be wrong or we could work with something in the middle, such as reducing the rate in which the frames are displayed.

So, I still want to have FFmpeg as an option for importing videos though.

**Comment by manbokGo** [comment]
Oh I meant you probably would feel my code is a bit poor when you analyze it. I have no intention to refuse your analyze or merge. Sorry about serious miscommunications. I don't speak English well. :(
I understand and totally agree with all of your opinion, keep it up!

**Pull request closed without merging**
