### PR TITLE
Update Korean language

### PR DESCRIPTION
**Pull request by manbokGo**
Complete all untranslated keys.

### CODE REVIEW

**Comment by NickeManarin** [comment]
Thank you. Do you wish to add your name or nickname as the author of the translation?

**Comment by manbokGo** [comment]
Yes. "Manbok" please. :)

**Comment by manbokGo** [comment]
@NickeManarin 
I think my translation is reverted back on current 2.19 version. Please check it.

**Comment by NickeManarin** [comment]
It's working with v2.19.1, but I forgot to add your name as author, I'm going to create another version during the weekend fixing this issue.

**Comment by NickeManarin** [comment]
I'll check it.

**Comment by NickeManarin** [comment]
Open the app again, it should be updated now.

**Pull request merged**
