### PR TITLE
Possibility to align text within free text

### PR DESCRIPTION
**Pull request by mabakay**
I have added combobox under text field. It allows to select from four options: Left, Center, Right, Justify. With "Justify" there is available one more numer field for blocking text canvas width (needed from obvious reasons).
 
**Example of "Center"**
image

**Example of "Justify"**
image

### CODE REVIEW

**Comment by NickeManarin** [comment]
Great, nicely done and well organized.

How do you feel about the "Alignment" being inside the "Layout" or "Font"?

**Comment by mabakay** [comment]
Alignment doesn't seem as Font property IMO but hej! It yours project so you decide. Move it to top of Layout group or at bottom?

**Comment by NickeManarin** [comment]
Bottom, I think.

**Comment by mabakay** [comment]
image

**Comment by NickeManarin** [comment]
Perfect, thanks!

**Pull request merged**
