### PR TITLE
Preview Playback: Speeds up by nearly 50%

### PR DESCRIPTION
**Pull request by mabakay**
I have noticed that two other image controls (fade and slide effects preview) are bonded to the same image control which is used by preview play to display frames in a way that evaluates theirs bindings during playback. I have changed this by adding a condition for effect panel visibility.

In result preview playback works now roughly...**50% faster**. No kidding :-)

My pull request consists of two commits.

1. First one "Do not update fade and slide effects preview images when not shown" is essential for this speed boost. It makes these bindings being applied through effects panel visibility condition.
2. Second one "Change panel visibility to hidden after close of right panel" well...it extends code that is already there (which change visibility of last shown panel just before showing next panel) to do the same thing just after cancel or close of effects panel. **Purpose of this commit is to maintain conditional binding - without it after applying fade or slide effect additional bindings will still evaluate (unnecessarily) until some other panel is shown (and visibility of last opened will be change to hidden)**.
It is not clear to me why this was not happening so far. I thought that this can be intentional because of process of applying effects after closing the panel. That is why I mention it and bring it to your attention. I have tested some effect apply functionality (I mean fade and slide) and it seems to work. But this second commit touches probably every available effect. So I ask here what do you think about it? @NickeManarin 

Both commits are independent of each other.

### CODE REVIEW

**Comment by NickeManarin** [comment]
Looks good. No issues that I could find.

I just could not detect a performance improvement. 
Maybe this issue was causing negligible performance impacts on my machine, but it was cause worse for others.

Now the panels are hidden before the animation of closing happens, same as the "Save As" panel which I recently altered.

**Comment by mabakay** [comment]
> I just could not detect a performance improvement.
> Maybe this issue was causing negligible performance impacts on my machine, but it was cause worse for others.

Negligible performance impacts? I am writing about cutting in half the time needed to display the image on the main control of the editor window. Not only during playback, but for each image change in this view - crucial to any operation that changes this view in batch mode such as preview playback. I use frames in 720p or greater for benchmark. Times as cut from 44ms to 21ms (average in release mode). It is 22 FPS vs 47 FPS!

The measurement of this change can be made by measuring the time of frame change during playback. **I added a sample "Frame change benchmark" commit to the repository branch.**

Changing SelectedIndex

`// Change active frame`
`Dispatcher.Invoke(() => FrameListView.SelectedIndex = selectedIndex);`

Changes three controls instead of one. And since they all use UriToBitmapConverter it gets called three times every time the frame changes. ImageMethods.SourceFrom is called, reads and decodes the same image three times.

Yea right the stream on the disk will be cached by system after the first read and it won't matter much whether we are reading from HDD or SSD, but decoding and displaying is still done many times even though it is not needed.

I have eight thread i7 with 3.50 GHz core speed, 16 GB RAM with SSD and it does not seem to be "negligible".

**Comment by mabakay** [comment]
> Now the panels are hidden before the animation of closing happens, same as the "Save As" panel which I recently altered.

Fix in "Hiding last panel after storyboard completes" commit by hooking method to storyboard completed event instead invoking from close panel method.

But one more time. For performance change crucial is only one (the first tinny) commit - "Do not update fade and slide effects preview images when not shown". Changes in Open/Close panel methods are made only to preserve consistent behavior either user opens fade or slide panel during application session or not.

I hope it seems reasonable for you.

**Comment by NickeManarin** [comment]
> Negligible performance impacts? I am writing about cutting in half the time needed to display the image on the main control of the editor window. Not only during playback, but for each image change in this view - crucial to any operation that changes this view in batch mode such as preview playback. I use frames in 720p or greater for benchmark. Times as cut from 44ms to 21ms (average in release mode). It is 22 FPS vs 47 FPS!

I'm sorry if my sentence sounded like I was criticizing your work. It was not what I wanted.
I was criticizing myself for not being able to detect/test changes in the performance, then I tried to explain why, putting the fault in my system (i7 8700k @ 5GHz, 16GB RAM @ 3.200Mhz, SSD NVMe 3Gbps read speeds).

**Comment by mabakay** [comment]
> I'm sorry if my sentence sounded like I was criticizing your work. It was not what I wanted.

None taken. I assumed we just focused on testing different elements. I wanted to emphasize that this behavior may look inconspicuous but IMHO has a much wider functional impact than just playback.

I looked at the issues list and guess what I found - Looking frames starts to slowdown #473.

> ...as i go through the frames using the right key from the keyboard, at start it is very fast, and as it approaches to 500, 600 and so, it starts to be VERY slow...

I doubt that my proposal will solve this problem, but frame-to-frame transition should certainly be faster in this case.

**Comment by NickeManarin** [comment]
I'm on another computer, testing multiple times gave me these results on a 60fps capture:

dev:
Frame time avg: 36
Frame time avg: 28
Frame time avg: 29
Frame time avg: 28

pr/878:
Frame time avg: 44
Frame time avg: 24
Frame time avg: 19
Frame time avg: 19

**Comment by mabakay** [comment]
Hey, 28 ms and 19 ms per frame is still >30% gain. Or otherwise 35 FPS vs 52 FPS. Is it worth it for just few lines of a pure XAML? ¯\_( ͠• ͜ʖ ͡•)_/¯

**Comment by NickeManarin** [comment]
Your changes are better, clearly :)

Can you just drop the commit with the benchmark? Then I'll merge it :)

**Pull request merged**
