### PR TITLE
Free text tool can now decorate text and add shadow effect

### PR DESCRIPTION
**Pull request by mabakay**
I have added combobox that allows to select from five text decoration options: None, Underline, Strikethrough, OverLine and Baseline. Examples below

image

There is also possibility to apply text shadow effect in a separate section

image

### CODE REVIEW

**Comment by mabakay** [comment]
Any thoughts about UI?

**Comment by NickeManarin** [comment]
Hi, sorry the delay.

Overall the feature is good, I just didn't like how the shadow is applied or not by expanding the expander element.
How does other software deal with that?

Maybe you can leave the blur radius as zero by default?

**Comment by mabakay** [comment]
> Overall the feature is good, I just didn't like how the shadow is applied or not by expanding the expander element.
How does other software deal with that?

Shadow is non exclusive effect so it has to be enabled by switch or flag within other effects. Maybe simple checkbox (on/off) instead of expand/collapse will do the job?

image

> Maybe you can leave the blur radius as zero by default?

Not a problem. Defaults was set from .NET MSDN class.

**Comment by NickeManarin** [comment]
My mistake, I meant the opacity of the shadow as zero instead of the blur radius, so if the user wants to apply a shadow, it must increase the opacity.

This way, no checkbox would be needed. What do you think?

I was looking at how this feature is usually laid out by other apps. They have a preset system in which one of the options is set to zero opacity.

**Comment by mabakay** [comment]
> I meant the opacity of the shadow as zero instead of the blur radius, so if the user wants to apply a shadow, it must increase the opacity.
> 
> This way, no checkbox would be needed. What do you think?

Great idea! Done.

PS @dagdelenvolkan needs to check translations he pushed. There are xml syntax errors.

**Comment by NickeManarin** [comment]
Awesome. Good job!

I ended up fixing the issues with the Turkish localization.

**Pull request merged**
