### PR TITLE
Upload to cloud

### PR DESCRIPTION
**Pull request by om2804**
Refactoring of uploading (Imgur, Gfycat). Add Yandex.Disk service.

### CODE REVIEW

**Comment by NickeManarin** [comment]
Thank you for improving the upload system. :)

[Also: please, before submitting any PR, read the rules.](https://github.com/NickeManarin/ScreenToGif/blob/master/CONTRIBUTING.md)

This project requires us to avoid external DLL's to keep the same level of portability.

So **ScreenToGif.Cloud** and **ScreenToGif.Cloud.Yandex** can be merged with the main project and any reference to **Newtonsoft.Json** can be replaced by **JavaScriptSerializer**. 

Unfortunatelly, this will require some work at line 29 of _YandexDisk.cs_ with the usage of a Dictionary.

**Comment by om2804** [comment]
> So ScreenToGif.Cloud and ScreenToGif.Cloud.Yandex can be merged with the main project
It's no good idea. This makes extensibility impossible and connecting additional loading services like plug-ins.

> Every feature should be packed into the main executable, unless it's optional like FFmpeg.
What advantages does it give?

> Unfortunatelly, this will require some work at line 29 of YandexDisk.cs with the usage of a Dictionary.
I do not understand what it is about.

**Comment by NickeManarin** [comment]
> It's no good idea. This makes extensibility impossible and connecting additional loading services like plug-ins.

It's one my goals to be able to use the app with just the main executable. As a no-install, single .exe profile. It's still possible to add support for plugins and external tools such of what I'm doing with FFmpeg and Gifski.

> What advantages does it give?

Portability basically. The app was born with that in mind. Some people don't like to install apps or even keep carrying folders with extra files. So, that's I created a single executable. 
Maybe someday I'll stop distributing it as a single executable, but I'll have to create some polls to see how many people will be affected.  :(

> I do not understand what it is about :)

At the line number 29, there's some code that uses the **Newtonsoft.Json** library, if it's going to be switched to a native/vanilla reference such as [JavaScriptSerializer](https://msdn.microsoft.com/en-us/library/system.web.script.serialization.javascriptserializer(v=vs.110).aspx), some work needs to be done in order to adapt the code.

**Comment by om2804** [comment]
> Portability basically. 

You can use the packer (ilmerge).

> Some people don't like to install apps or even keep carrying folders with extra files.

These are maniacs :)
This shifts the installer's responsibilities to the executable file. For example, editing the registry. And here there can be problems with the rights.

> JavaScriptSerializer

May be System.Runtime.Serialization.Json.DataContractJsonSerializer ?

> Maybe someday I'll stop distributing it as a single executable

The time has come. Now! :)

**Comment by NickeManarin** [comment]
> You can use the packer (ilmerge).

I was using a similar method back when the app was at version 0.3, it was giving me a lot of false positives with anti-virus apps. It was basically a hack that I had to apply every time that I compiled the app. :/

> These are maniacs :)
This shifts the installer's responsibilities to the executable file. For example, editing the registry. And here there can be problems with the rights.

I'm a maniac :O
Yeah, but I don't write data on the registry. I keep a XAML file at the `%APPDATA%/ScreenToGif` (unless specified to be elsewhere) with all the settings.

> May be System.Runtime.Serialization.Json.DataContractJsonSerializer ?

DataContractJsonSerializer requires you to know the content of the JSON. If you know it, you just need to create the model class with the required attributes on each property.

**Comment by om2804** [comment]
Ok. I did this "for myself". You can fix it yourself or I can fix it myself, but later.

**Pull request merged**
