### PR TITLE
Close #743 Add .editorconfig

### LINKED ISSUE #743: Add .editorconfig file to project to help maintain consistent coding style
It makes the project better consistent coding style

https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options
https://github.com/dotnet/runtime/blob/master/.editorconfig

### PR DESCRIPTION
**Pull request by hantatsang**
Close #743 

Add `.editorconfig` to help maintain a consistent coding style.

- Dotnet rules are too lengthy, so use the template from https://github.com/RehanSaeed/EditorConfig and stick to that coding style, which already seems to work fine with ScreenToGif's current codebase
- Add a few custom rules for this codebase

This will help clean up existing code a lot while editing them by removing trailing white spaces, keeping indentation consistent, etc.

### CODE REVIEW

**Comment by hantatsang** [comment]
I decided to remove the rules copied from https://github.com/RehanSaeed/EditorConfig 

The rules don't follow the existing coding style in the code. In addition, they're too long and starting with too many rules now doesn't seem to be a good start. Those custom DotNet/C# rules are also too hard to read and tweak, I don't know if you'd ever even want to add them.

**Comment by NickeManarin** [comment]
Hi, sorry for the delay. 

I'm not sure about this editor config. I use Resharper on my end.
Is there any way to integrate the settings that I use with the .editorconfig?

**Comment by hantatsang** [comment]
Hi,

I use Rider and I think there's a built-in EditorConfig plugin that supports it.
On Visual Studio there's [MadsKristensen.EditorConfig](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.EditorConfig)

For Visual Studio Code there's also an [EditorConfig plugin](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)

I think if you want to accept this PR, then a good idea is to add a guideline in `CONTRIBUTING.md` that contributors should enable EditorConfig plugin to keep code format consistent.

**Comment by hantatsang** [comment]
Any updates @NickeManarin ?

**Pull request merged**
