### PR TITLE
Theme: Allow to set up theme to follow system theme.

### LINKED ISSUE #898: [Feature request] Switching dark/light color theme automatically
Hello!
I suggest to add the function of switching dark/light color theme automatically with the system in order to make the application more coordinated with the system.
Thanks!

### PR DESCRIPTION
**Pull request by pawlos**
Currently it only works when the change of the theme in application occurs 
(or when the application starts) as WPF (probably) doesn't have any event exposed 
to react when the change occurs in real time.

This (probably) closes #898

### CODE REVIEW

**Comment by NickeManarin** [comment]
Have you tried to listen to `SystemEvents.UserPreferenceChanged` ?

**Comment by pawlos** [comment]
@NickeManarin Yes, It's been firing multiple times with no info about the theme, but maybe with the regestry reading it could be done. Let me re-check that again.

**Comment by pawlos** [comment]
@NickeManarin actually it worked. I was looking for something like `ThemeChanged` info in `UserPreferenceChangedEventArgs` but it was all the time `General`. But with this event and reading the registry application is reacting real time to theme changes.

**Comment by NickeManarin** [comment]
Thanks.

**Pull request merged**
