### PR TITLE
Update StringResources.nl.xaml

### PR DESCRIPTION
**Pull request by Stephan-P**
Updates for 2.24.2
Transformed all formal language into informal addressing

### CODE REVIEW

**Comment by NickeManarin** [comment]
Thanks.

**Comment by Stephan-P** [comment]
Hello Nicke,

I didn't realise that there would be translation updates necessary until this burst of daily program updates passed by. Would it be possible to send out a brief "please update the translation" request when new strings have been introduced?

I am very pleased with new option to perform the update under elevated privileges. I hope that the standard downloadable installer now also is marked to require admin rights. There have been many times that the installation process was halfway interrupted for lack of privileges, because I forgot to explicitly start the executable "as administrator". Generally an installer would ask for the admin password or an OK for elevation of rights.

May I ask one other thing about the installer language? My windows installation is in Dutch language. This language is not available in the installer, which is alright. But  If I click through too fast, I get stuck in Brasilian Portuguese, which is all Greek to me. Could the default language, in cases where there is no match with the host, be set to English?

Cheers, Stephan

Stephan Paternotte
---------------------------------------------
E: stephan@paternottes.net

________________________________

**Comment by NickeManarin** [comment]
Hello Stephan,

> Would it be possible to send out a brief "please update the translation" request when new strings have been introduced?

Overall, new translatable texts are added when a minor release (2.23 -> 2.24) is launched. You can set to watch "releases only" on this repository in order to receive updates.

I've tried once to send emails briefs but I ended up forgetting about it after a couple of releases. I need to improve my release workflow in order to add more tasks.

>  I hope that the standard downloadable installer now also is marked to require admin rights. 

The installer was set to always require admin rights when installing, but an user complained that the installer was unnecessarily asking for admin rights, then I set to ask only when necessary.

Looks like it's not working as expected. Can you give me an example of install folder so I can test on my machine?

By the way, the UAC prompt should appear when setting to install the shortcut to all users.

> This language is not available in the installer, which is alright.

If you wish to help with the installer translation too, here's how: https://github.com/NickeManarin/ScreenToGif/wiki/Localization-(Installer)

> But  If I click through too fast, I get stuck in Brazilian Portuguese, which is all Greek to me.

That's not supposed to be happening. It should default to English when the computers language is set to a missing translation. I'll have to take a look at it.

**Comment by Stephan-P** [comment]
Piece of cake.

Stephan Paternotte
Amsterdam
Nederland
--------------------------
E: stephan@paternottes.net<mailto:stephan@paternottes.net>

Van: Nicke Manarin<mailto:notifications@github.com>
Verzonden: dinsdag 19 mei 2020 18:09
Aan: NickeManarin/ScreenToGif<mailto:ScreenToGif@noreply.github.com>
CC: Stephan Paternotte<mailto:stephan@paternottes.net>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [NickeManarin/ScreenToGif] Update StringResources.nl.xaml (#657)


Hello Stephan,

Would it be possible to send out a brief "please update the translation" request when new strings have been introduced?

Overall, new translatable texts are added when a minor release (2.23 -> 2.24) is launched. You can set to watch "releases only" on this repository in order to receive updates.

I've tried once to send emails briefs but I ended up forgetting about it after a couple of releases. I need to improve my release workflow in order to add more tasks.

I hope that the standard downloadable installer now also is marked to require admin rights.

The installer was set to always require admin rights when installing, but an user complained that the installer was unnecessarily asking for admin rights, then I set to ask only when necessary.

Looks like it's not working as expected. Can you give me an example of install folder so I can test on my machine?

By the way, the UAC prompt should appear when setting to install the shortcut to all users.

This language is not available in the installer, which is alright.

If you wish to help with the installer translation too, here's how: https://github.com/NickeManarin/ScreenToGif/wiki/Localization-(Installer)

But If I click through too fast, I get stuck in Brazilian Portuguese, which is all Greek to me.

That's not supposed to be happening. It should default to English when the computers language is set to a missing translation. I'll have to take a look at it.

**Comment by Stephan-P** [comment]
Hello Nicke,

I have to take something back, as I've been mistaken.
It's ocenaudio an dnot screentogif that is having these two issues with the installer:

  *   default language Portuguese
  *   failing to ask for elevated installation rights

My bad entirely for having confused two apps of Brasilian origin.
So, please enjoy my Dutch translation for the installer and forget about the other things I mentioned as they have nothing to do with your app.
My sincere apologies.

Kind regards,
Stephan
________________________________
Van: Nicke Manarin <notifications@github.com>
Verzonden: dinsdag 19 mei 2020 18:09
Aan: NickeManarin/ScreenToGif <ScreenToGif@noreply.github.com>
CC: Stephan Paternotte <stephan@paternottes.net>; Author <author@noreply.github.com>
Onderwerp: Re: [NickeManarin/ScreenToGif] Update StringResources.nl.xaml (#657)


Hello Stephan,

Would it be possible to send out a brief "please update the translation" request when new strings have been introduced?

Overall, new translatable texts are added when a minor release (2.23 -> 2.24) is launched. You can set to watch "releases only" on this repository in order to receive updates.

I've tried once to send emails briefs but I ended up forgetting about it after a couple of releases. I need to improve my release workflow in order to add more tasks.

I hope that the standard downloadable installer now also is marked to require admin rights.

The installer was set to always require admin rights when installing, but an user complained that the installer was unnecessarily asking for admin rights, then I set to ask only when necessary.

Looks like it's not working as expected. Can you give me an example of install folder so I can test on my machine?

By the way, the UAC prompt should appear when setting to install the shortcut to all users.

This language is not available in the installer, which is alright.

If you wish to help with the installer translation too, here's how: https://github.com/NickeManarin/ScreenToGif/wiki/Localization-(Installer)

But If I click through too fast, I get stuck in Brazilian Portuguese, which is all Greek to me.

That's not supposed to be happening. It should default to English when the computers language is set to a missing translation. I'll have to take a look at it.

**Comment by NickeManarin** [comment]
Ohh. Ok. :)

Did you send the installer translation through the email attachment? 
Because it's not showing it.

**Pull request merged**
